// Esse código será apenas utilizado porque não é necessário o uso do back-end

import { Categoria } from "../interface/Categoria";
import { Produto } from "../interface/Produto";

const vara: Categoria = { id: 1, nome: "Varas", slug: "vara" }
const linha: Categoria = { id: 2, nome: "Linhas", slug: "linha" }
const carretilha: Categoria = { id: 3, nome: "Carretilhas", slug: "carretilha" }
const chumbada: Categoria = { id: 4, nome: "Chumbadas", slug: "chumbada" }
const url = "/desweb/imagens";
const produtos: Produto[] = [
  // Varas
  {
    id: 1,
    imagem: url + "/vara1.jpg",
    categoria: vara,
    nome: "Vara de Pesca Shimano FX",
    slug: "vara-shimano-fx",
    descricao: "Vara de pesca leve, ideal para iniciantes e pescarias em água doce.",
    disponivel: true,
    dataCadastro: new Date(),
    qtdEstoque: 12,
    preco: 199.90,
  },
  {
    id: 2,
    imagem: url + "/vara2.jpg",
    categoria: vara,
    nome: "Vara Marine Sports Solara",
    slug: "vara-marine-sports-solara",
    descricao: "Modelo resistente e versátil para diversas modalidades de pesca.",
    disponivel: true,
    dataCadastro: new Date(),
    qtdEstoque: 8,
    preco: 249.90,
  },
  {
    id: 3,
    imagem: url + "/vara3.jpg",
    categoria: vara,
    nome: "Vara Saint Plus Evolution",
    slug: "vara-saint-plus-evolution",
    descricao: "Excelente ação rápida com acabamento de alta qualidade.",
    disponivel: true,
    dataCadastro: new Date(),
    qtdEstoque: 5,
    preco: 319.90,
  },
  {
    id: 4,
    imagem: url + "/vara4.jpg",
    categoria: vara,
    nome: "Vara Daiwa Laguna",
    slug: "vara-daiwa-laguna",
    descricao: "Desmoderno e ótimo desempenho em pescarias costeiras.",
    disponivel: false,
    dataCadastro: new Date(),
    qtdEstoque: 0,
    preco: 289.90,
  },
  {
    id: 5,
    imagem: url + "/vara5.jpg",
    categoria: vara,
    nome: "Vara Albatroz Black Fish",
    slug: "vara-albatroz-black-fish",
    descricao: "Boa resistência para peixes maiores e estrutura reforçada.",
    disponivel: true,
    dataCadastro: new Date(),
    qtdEstoque: 10,
    preco: 16.90,
  },

  // Linhas
  {
    id: 6,
    imagem: url + "/linha1.jpg",
    categoria: linha,
    nome: "Linha Monofilamento Araty",
    slug: "linha-monofilamento-araty",
    descricao: "Linha de nylon transparente, ideal para pesca leve.",
    disponivel: true,
    dataCadastro: new Date(),
    qtdEstoque: 20,
    preco: 19.90,
  },
  {
    id: 7,
    imagem: url + "/linha2.jpg",
    categoria: linha,
    nome: "Linha Multifilamento Power Pro",
    slug: "linha-multifilamento-power-pro",
    descricao: "Alta resistência e sensibilidade, excelente para pesca esportiva.",
    disponivel: true,
    dataCadastro: new Date(),
    qtdEstoque: 15,
    preco: 89.90,
  },
  {
    id: 8,
    imagem: url + "/linha3.jpg",
    categoria: linha,
    nome: "Linha Fluorocarbono Seaguar",
    slug: "linha-fluorocarbono-seaguar",
    descricao: "Invisível na água, ideal para ambientes com muita pressão de pesca.",
    disponivel: true,
    dataCadastro: new Date(),
    qtdEstoque: 7,
    preco: 99.90,
  },
  {
    id: 9,
    imagem: url + "/linha4.jpg",
    categoria: linha,
    nome: "Linha de Pesca Maruri Max Force",
    slug: "linha-maruri-max-force",
    descricao: "Linha durável e confiável, com bom custo-benefício.",
    disponivel: false,
    dataCadastro: new Date(),
    qtdEstoque: 0,
    preco: 29.90,
  },
  {
    id: 10,
    imagem: url + "/linha5.jpg",
    categoria: linha,
    nome: "Linha YGK G-soul Upgrade",
    slug: "linha-ygk-g-soul-upgrade",
    descricao: "Linha japonesa premium com alta performance.",
    disponivel: true,
    dataCadastro: new Date(),
    qtdEstoque: 4,
    preco: 149.90,
  },

  // Carretilhas
  {
    id: 11,
    imagem: url + "/carretilha1.jpg",
    categoria: carretilha,
    nome: "Carretilha Shimano SLX",
    slug: "carretilha-shimano-slx",
    descricao: "Desempenho suave e estrutura compacta para pescarias exigentes.",
    disponivel: true,
    dataCadastro: new Date(),
    qtdEstoque: 6,
    preco: 499.90,
  },
  {
    id: 12,
    imagem: url + "/carretilha2.jpg",
    categoria: carretilha,
    nome: "Carretilha Daiwa Fuego",
    slug: "carretilha-daiwa-fuego",
    descricao: "Excelente custo-benefício e boa capacidade de linha.",
    disponivel: true,
    dataCadastro: new Date(),
    qtdEstoque: 9,
    preco: 459.90,
  },
  {
    id: 13,
    imagem: url + "/carretilha3.jpg",
    categoria: carretilha,
    nome: "Carretilha Marine Sports Titan",
    slug: "carretilha-marine-sports-titan",
    descricao: "Robusta e confiável, ideal para peixes de grande porte.",
    disponivel: true,
    dataCadastro: new Date(),
    qtdEstoque: 3,
    preco: 379.90,
  },
  {
    id: 14,
    imagem: url + "/carretilha4.jpg",
    categoria: carretilha,
    nome: "Carretilha Abu Garcia Revo",
    slug: "carretilha-abu-garcia-revo",
    descricao: "Modelo top de linha com desempenho excepcional.",
    disponivel: false,
    dataCadastro: new Date(),
    qtdEstoque: 0,
    preco: 799.90,
  },
  {
    id: 15,
    imagem: url + "/carretilha5.jpg",
    categoria: carretilha,
    nome: "Carretilha Albatroz Fire",
    slug: "carretilha-albatroz-fire",
    descricao: "Boa ergonomia e ótimo desempenho em pescarias costeiras.",
    disponivel: true,
    dataCadastro: new Date(),
    qtdEstoque: 11,
    preco: 269.90,
  },

  // Chumbadas
  {
    id: 16,
    imagem: url + "/chumbada1.jpg",
    categoria: chumbada,
    nome: "Chumbada Pirâmide 50g",
    slug: "chumbada-piramide-50g",
    descricao: "Ideal para pesca em praias com correnteza forte.",
    disponivel: true,
    dataCadastro: new Date(),
    qtdEstoque: 40,
    preco: 4.90,
  },
  {
    id: 17,
    imagem: url + "/chumbada2.jpg",
    categoria: chumbada,
    nome: "Chumbada Oliva 30g",
    slug: "chumbada-oliva-30g",
    descricao: "Boa performance em lagos e rios de corrente fraca.",
    disponivel: true,
    dataCadastro: new Date(),
    qtdEstoque: 50,
    preco: 3.90,
  },
  {
    id: 18,
    imagem: url + "/chumbada3.jpg",
    categoria: chumbada,
    nome: "Chumbada Bola 100g",
    slug: "chumbada-bola-100g",
    descricao: "Peso ideal para pesca de fundo com iscas naturais.",
    disponivel: true,
    dataCadastro: new Date(),
    qtdEstoque: 30,
    preco: 5.90,
  },
  {
    id: 19,
    imagem: url + "/chumbada4.jpg",
    categoria: chumbada,
    nome: "Chumbada Disco 80g",
    slug: "chumbada-disco-80g",
    descricao: "Design achatado que evita rolamentos em rios.",
    disponivel: false,
    dataCadastro: new Date(),
    qtdEstoque: 0,
    preco: 5.50,
  },
  {
    id: 20,
    imagem: url + "/chumbada5.jpg",
    categoria: chumbada,
    nome: "Chumbada Palito 20g",
    slug: "chumbada-palito-20g",
    descricao: "Ideal para pesca de arremesso com precisão.",
    disponivel: true,
    dataCadastro: new Date(),
    qtdEstoque: 60,
    preco: 2.90,
  }
];

const recuperarProdutos = () => {
  console.log("executando recuperarProdutos()...");
  return new Promise<Produto[]>((resolve) => {
    setTimeout(() => {
      resolve(produtos);
    }, 2000)
  })
  // return produtos;
}

export default recuperarProdutos
